apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-serivce
  namespace: default
spec:
  selector:
    app: nodejs-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 80
    port: 80
